# Generated by Django 2.0.1 on 2018-02-20 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalleImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPagina', models.IntegerField(default=1)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('titulo', models.CharField(max_length=80)),
                ('descripcioncorta', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=1300)),
                ('tipo', models.CharField(choices=[('A', 'Incio'), ('B', 'Final'), ('C', 'Normal')], default='C', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='imagenVista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('activo', models.CharField(choices=[('A', 'Activo'), ('B', 'Normal')], default='B', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fondo', models.ImageField(upload_to='imagenes/')),
                ('fondomovil', models.ImageField(upload_to='imagenes/')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.AddField(
            model_name='detalleimagen',
            name='imagenVistaDetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detallel.imagenVista'),
        ),
    ]
