# Generated by Django 2.0.4 on 2018-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenvista',
            name='link',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
